dataset:
  _target_: "nemo.collections.tts.torch.data_ssl_vocoder.SSLVocoderDataset"
  manifest_filepath: ${validation_datasets}
  ssl_model_type: ${ssl_model_type}
  ssl_model_ckpt_path: ${ssl_model_ckpt_path}
  ssl_content_emb_type: ${ssl_content_emb_type}
  sample_rate: ${sample_rate}
  n_segments: ${val_n_segments}
  max_duration: ${val_max_duration}
  min_duration: ${val_min_duration}
dataloader_params:
  drop_last: false
  shuffle: false
  batch_size: 16
  num_workers: 1
  pin_memory: true
